services:
  - type: web
    name: chatterbot-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.13
      - key: BOT_TOKEN
        value: your_token_here
      - key: WEBHOOK_URL
        value: https://your-subdomain.onrender.com/webhook
      - key: ADMIN_ID
        value: "7617589302"
